

### Request to atg_process Azure Function
POST http://localhost:7071/api/atg_process
Content-Type: application/json

{
    "prefix_list": [""]
}

# ### Status endpoint
# GET http://localhost:7071/api/status
# Content-Type: application/json

